[build-system]
requires = [ "setuptools>=60", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ngsolve_gui"
dynamic = ["version"]
dependencies = ["ngapp>=0.4.2", "ngsolve_webgpu>=0.4.0", "webgpu>=1.4.0", "ngsolve", "numpy", "psutil", "anywidget", "requests"]

[project.optional-dependencies]
gpu-monitor = ["pynvml"]
plotting = ["plotly", "matplotlib"]
interactive = ["IPython"]

[project.scripts]
ngsolve = "ngsolve_gui.run:main"
ngsolve_gui = "ngsolve_gui.run:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_file = "src/ngsolve_gui/_version.py"
local_scheme = "no-local-version"

