[build-system]
requires = [ "setuptools>=60", "wheel", "setuptools-scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "ngsolve_gui"
dynamic = ["version"]
dependencies = ["ngapp>=0.3.7", "ngsolve_webgpu>=0.3.1", "webgpu", "ngsolve", "numpy", "psutil"]

[project.optional-dependencies]
gpu-monitor = ["pynvml"]
plotting = ["plotly", "matplotlib"]
interactive = ["IPython"]

[project.scripts]
ngsolve = "ngsolve_gui.run:main"
ngsolve_gui = "ngsolve_gui.run:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {attr = "ngsolve_gui.__version__"}

