from .clipping import ClippingSection
from .colorbar import ColorbarSection
from .deformation import DeformationSection
from .vectors import VectorSection
from .fieldlines import FieldLinesSection
from .mesh_view import MeshViewSection
from .mesh_colors import MeshColorSection
from .function_options import FunctionOptionsSection
from .geometry_options import GeometryOptionsSection
from .geometry_selection import GeometrySelectionSection
from .entity_numbers import EntityNumbersSection
